# Site settings
title: 프레드리크의 블로그
url: "https://junseokyoon.github.io"
baseurl: ""
description: >
    개인 위키 블로그

# My information
email: your-email@example.com
author: 프레드리크
github_username: junseokyoon

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
  wiki:
    output: true
    permalink: /wiki/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
      type: wiki

blame: "https://github.com/junseokyoon/junseokyoon.github.io/blame/master/_wiki"
edit: "https://github.com/junseokyoon/junseokyoon.github.io/edit/master/_wiki"
issue: "https://github.com/junseokyoon/junseokyoon.github.io/issues/new"

timezone: "Asia/Seoul"

# Exclude files from Jekyll build
exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .github
